name: rtdvenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python={% if cookiecutter.support_py37 == 'y' %}3.7{% elif cookiecutter.support_py36 == 'y' %}3.6{% elif cookiecutter.support_py35 == 'y' %}3.5{% elif cookiecutter.support_py34 == 'y' %}3.4{% else %}3{% endif %}
{%- set pkg_list = cookiecutter.conda_packages.split() -%}
{%- for pkg in pkg_list %}
  - {{ pkg }}
{%- endfor %}
  - pip:
    - sphinx-autodoc-typehints
    - gitpython
{%- if cookiecutter.better_apidoc == 'y' %}
    - better-apidoc
{%- endif %}
{%- if cookiecutter.use_notebooks == 'y' %}
    - nbsphinx
{%- endif %}
