environment:

  matrix:
{%- if cookiecutter.support_py35 == 'y' %}
    - PYTHON: "C:\\Python35"
      TOXENV: py35-test
{%- endif %}
{%- if cookiecutter.support_py36 == 'y' %}
    - PYTHON: "C:\\Python36"
      TOXENV: py36-test
{%- endif %}
{%- if cookiecutter.support_py37 == 'y' %}
    - PYTHON: "C:\\Python37"
      TOXENV: py37-test
{%- endif %}
{%- if cookiecutter.support_py38 == 'y' %}
    - PYTHON: "C:\\Python38"
      TOXENV: py38-test
{%- endif %}
{%- if cookiecutter.support_py39 == 'y' %}
    - PYTHON: "C:\\Python39"
      TOXENV: py39-test
{%- endif %}

install:
  - "%PYTHON%\\python.exe -V"
  - "%PYTHON%\\python.exe -m pip install tox"
  - "%PYTHON%\\python.exe -m pip freeze"

build: off

test_script:
  - "%PYTHON%\\python.exe -m tox -vv -e %TOXENV%"
