environment:

  matrix:
{%- if cookiecutter.support_py35 == 'y' %}
    - PYTHON_VERSION: 3.5
      MINICONDA: C:\Miniconda3
{%- endif %}
{%- if cookiecutter.support_py36 == 'y' %}
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda3
{%- endif %}

install:
  - "%MINICONDA%\\Scripts\\activate"
  - conda config --set always_yes yes
  - conda create -q -n test_env python=%PYTHON_VERSION% {{ cookiecutter.conda_packages }}
  - activate test_env
  - echo CONDA_PREFIX %CONDA_PREFIX%
  - echo PATH %PATH%
  - conda config --append channels conda-forge
  - pip install .[dev]
  - pip freeze

build: off

test_script:
  - ps: pytest --doctest-modules --cov={{ cookiecutter.project_slug }} src tests (get-item docs\*.rst).FullName
