version: 2
formats:
    - htmlzip
build:
    image: latest
python:
    version: {{ cookiecutter.main_python }}
    install:
        - method: pip
          path: .
          extra_requirements:
            - dev
