# Config file for automatic testing at travis-ci.org

language: python
python:
{%- if cookiecutter.support_py36 == 'y' %}
  - 3.6
{%- endif %}
{%- if cookiecutter.support_py35 == 'y' %}
  - 3.5
{%- endif %}
{%- if cookiecutter.support_py34 == 'y' %}
  - 3.4
{%- endif %}

{%- if cookiecutter.environment_manager == 'conda' %}
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION {{ cookiecutter.conda_packages }}
  - source activate test-environment
  - pip install -e .[dev]
{%- if cookiecutter.coveralls == 'y' %}
  - pip install coveralls
{%- endif %}

script:
  - py.test --doctest-modules --cov={{ cookiecutter.project_slug }} src tests
{%- endif %}

{%- if cookiecutter.coveralls == 'y' %}
after_success:
  - coveralls
{%- endif %}
