# Config file for automatic testing at travis-ci.org
dist: xenial
language: python
python:
{%- if cookiecutter.support_py37 == 'y' %}
  - 3.7
{%- endif %}
{%- if cookiecutter.support_py36 == 'y' %}
  - 3.6
{%- endif %}
{%- if cookiecutter.support_py35 == 'y' %}
  - 3.5
{%- endif %}
{%- if cookiecutter.support_py34 == 'y' %}
  - 3.4
{%- endif %}

{%- if cookiecutter.environment_manager == 'conda' %}
install:
  # any failure stops the build
  - set -e
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda3
  - source $HOME/miniconda3/etc/profile.d/conda.sh
  - conda activate
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda create -q -n test_env python=$TRAVIS_PYTHON_VERSION {{ cookiecutter.conda_packages }}
  - conda activate test_env
  - conda config --append channels conda-forge
{%- if cookiecutter.coveralls == 'y' %}
  # we must use an editable install, otherwise coveralls won't work
{%- endif %}
  - PIP_USE_PEP517=false pip install -e .[dev]
  - pip freeze
{%- if cookiecutter.coveralls == 'y' %}
  - pip install coveralls
{%- endif %}
  - pip freeze

script:
  # any failure stops testing immediately
  - set -e
{% if cookiecutter.use_isort == 'y' %}
  - if [[ $TRAVIS_PYTHON_VERSION == {% if cookiecutter.support_py37 == 'y' %}'3.7'{% else %}'3.6'{% endif %} ]]; then isort --recursive --check-only src tests; fi
{% endif %}
{% if cookiecutter.use_black == 'y' %}
  - if [[ $TRAVIS_PYTHON_VERSION == {% if cookiecutter.support_py37 == 'y' %}'3.7'{% else %}'3.6'{% endif %} ]]; then black {% if cookiecutter.allow_single_quote_strings == 'y' %}--skip-string-normalization {% endif %}--line-length {{ cookiecutter.linelength }} --check src tests; fi
{% endif %}
  - pytest --doctest-modules --cov={{ cookiecutter.project_slug }} {%- if cookiecutter.use_notebooks == 'y' %} --nbval --sanitize-with docs/nbval_sanitize.cfg{% endif %} src tests docs/*.rst {%- if cookiecutter.use_notebooks == 'y' %} docs/*.ipynb{% endif %}
{%- endif %}

{%- if cookiecutter.coveralls == 'y' %}
after_success:
  - coveralls
{%- endif %}
