dist: xenial
language: generic
install:
  - set -e
  - cd /opt/pyenv/ && git fetch && git merge origin/master && cd -
  - pyenv install --list
  - pyenv install --skip-existing 3.5.7
  - pyenv install --skip-existing 3.8.1
  - pyenv global 3.5.7 3.6.7 3.7 3.8.1
  - pyenv versions
  - export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
  - travis_wait source .travis/texlive/texlive_install.sh
  - python3.7 -m pip install pytest-cookies ipython pdbpp black isort pre-commit flake8 pylint pep8 twine click gitpython doctr tox
  - python3.7 -m pip freeze
addons:
  apt_packages:
    - pandoc
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
    - /opt/pyenv
script:
  - python3.7 -m pytest -v -x -s tests
