name: binder
channels:
  - defaults
  - conda-forge
dependencies:
  - python={{ cookiecutter.main_python }}
  - pip:
    - matplotlib
    - watermark
    - git+https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}.git@{%- if cookiecutter.use_git_flow == 'y' -%}develop{%- else -%}master{%- endif -%}#egg={{ cookiecutter.project_slug }}
